src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Controllers/IdentityResourceController.cs
using Microsoft.AspNetCore.Authorization;

namespace GHPCommerce.IS4Admin.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using   Models.IdentityResourceModels;
    using IdentityServer4.EntityFramework.DbContexts;
    using IdentityServer4.EntityFramework.Entities;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Newtonsoft.Json;
   // [Authorize(Roles = "SuperAdmin,Admin")]
    public class IdentityResourceController : Controller
    {
        private readonly ConfigurationDbContext _configurationDbContext;

        public IdentityResourceController(ConfigurationDbContext configurationDbContext)
        {
            _configurationDbContext = configurationDbContext;
        }

        public IActionResult Index()
        {
            var itentities = _configurationDbContext.IdentityResources.ToList();
            return View(itentities.ToModels().ToList());
        }

        public IActionResult Add()
        {
            return View(nameof(Edit), new IdentityResourceModel());
        }

        public IActionResult Edit(int id)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.UserClaims)
                .FirstOrDefault(x => x.Id == id);
            return View(identity.ToModel());
        }

        [HttpPost]
        public IActionResult Edit(IdentityResourceModel model)
        {
            IdentityResource identity;
            if (model.Id == 0)
            {
                identity = new IdentityResource
                {
                    UserClaims = new List<IdentityClaim>(),
                };
                _configurationDbContext.IdentityResources.Add(identity);
            }
            else
            {
                identity = _configurationDbContext.IdentityResources
                    .Include(x => x.UserClaims)
                    .FirstOrDefault(x => x.Id == model.Id);
                identity.UserClaims.Clear();
            }

            model.UpdateEntity(identity);

            if (!string.IsNullOrEmpty(model.UserClaimsItems))
            {
                model.UserClaims = JsonConvert.DeserializeObject<List<string>>(model.UserClaimsItems);

                identity.UserClaims.AddRange(model.UserClaims.Select(x => new IdentityClaim
                {
                    Type = x,
                }));
            }

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = identity.Id });
        }

        public IActionResult Delete(int id)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.UserClaims)
                .FirstOrDefault(x => x.Id == id);
            return View(identity.ToModel());
        }

        [HttpPost]
        public IActionResult Delete(IdentityResourceModel model)
        {
            var identity = _configurationDbContext.IdentityResources
                .FirstOrDefault(x => x.Id == model.Id);

            _configurationDbContext.IdentityResources.Remove(identity);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Properties(int id)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.Properties)
                .FirstOrDefault(x => x.Id == id);
            return View(PropertiesModel.FromEntity(identity));
        }

        [HttpPost]
        public IActionResult AddProperty(PropertiesModel model)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.Properties)
                .FirstOrDefault(x => x.Id == model.IdentityResourceId);

            identity.Properties.Add(new IdentityResourceProperty
            {
                Key = model.Key,
                Value = model.Value,
            });

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Properties), new { id = identity.Id });
        }

        [HttpGet]
        public IActionResult DeleteProperty(int id)
        {
            var prop = _configurationDbContext.Set<IdentityResourceProperty>()
                .Include(x => x.IdentityResource)
                .FirstOrDefault(x => x.Id == id);
            return View(IdentityResourcePropertyModel.FromEntity(prop));
        }

        [HttpPost]
        public IActionResult DeleteProperty(IdentityResourcePropertyModel model)
        {
            var identity = _configurationDbContext.IdentityResources
                            .Include(x => x.Properties)
                            .FirstOrDefault(x => x.Id == model.IdentityResource.Id);
            var prop = identity.Properties.FirstOrDefault(x => x.Id == model.Id);
            identity.Properties.Remove(prop);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Properties), new { id = identity.Id });
        }

        public IActionResult GetClaims()
        {
            // http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
            var standardClaims = new List<string>
            {
                "name",
                "given_name",
                "family_name",
                "middle_name",
                "nickname",
                "preferred_username",
                "profile",
                "picture",
                "website",
                "gender",
                "birthdate",
                "zoneinfo",
                "locale",
                "address",
                "updated_at",
            };

            return Ok(standardClaims);
        }
    }
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Controllers/UserController.cs
using GHPCommerce.Core.Shared.Contracts.Indentity.Queries;
using Microsoft.AspNetCore.Authorization;

namespace GHPCommerce.IS4Admin.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Application.Membership.Roles.Queries;
    using Application.Membership.Users.Commands;
    using Application.Membership.Users.Queries;
    using CrossCuttingConcerns.OS;
    using GHPCommerce.Domain.Domain.Commands;
    using GHPCommerce.Domain.Domain.Identity;
    using Models.UserModels;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

//    [Authorize(Roles = "SuperAdmin,Admin")]
    public class UserController : Controller
    {
       
        private readonly ICommandBus _commandBus;
        private readonly UserManager<User> _userManager;
        private readonly IDateTimeProvider _dateTimeProvider;

        public UserController(ICommandBus commandBus,
            UserManager<User> userManager,
            ILogger<UserController> logger,
            IDateTimeProvider dateTimeProvider)
        {
           
            _commandBus = commandBus;
            _userManager = userManager;
            _dateTimeProvider = dateTimeProvider;
            logger.LogInformation("UserController");
        }

        public async Task<IActionResult> Index()
        {
            var users = await _commandBus.SendAsync(new GetUsersQuery { AsNoTracking = true });
            return View(users);
        }

        public async Task<IActionResult> Profile(Guid id)
        {
            var user = id != Guid.Empty
                ? await _commandBus.SendAsync(new GetUserQuery { Id = id, AsNoTracking = true })
                : new User();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(User model)
        {
            User user;
            if (model.Id != Guid.Empty)
            {
                user = await _commandBus.SendAsync(new GetUserQuery { Id = model.Id });
            }
            else
            {
                user = new User();
            }

            user.UserName = model.UserName;
            user.NormalizedUserName = model.UserName.ToUpper();
            user.Email = model.Email;
            user.NormalizedEmail = model.Email.ToUpper();
            user.EmailConfirmed = model.EmailConfirmed;
            user.PhoneNumber = model.PhoneNumber;
            user.PhoneNumberConfirmed = model.PhoneNumberConfirmed;
            user.TwoFactorEnabled = model.TwoFactorEnabled;
            user.LockoutEnabled = model.LockoutEnabled;
            user.LockoutEnd = model.LockoutEnd;
            user.AccessFailedCount = model.AccessFailedCount;

            _ = model.Id != Guid.Empty
                 ? await _userManager.UpdateAsync(user)
                 : await _userManager.CreateAsync(user);

            return RedirectToAction(nameof(Profile), new { user.Id });
        }

        public async Task<IActionResult> ChangePassword(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, AsNoTracking = true });
            return View(ChangePasswordModel.FromEntity(user));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, AsNoTracking = true });
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(User model)
        {
            await _commandBus.Send(new DeleteUserCommand { Id = model.Id });
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _commandBus.SendAsync(new GetUserQuery { Id = model.Id });
            var token = await _userManager.GeneratePasswordResetTokenAsync(user);
            var rs = await _userManager.ResetPasswordAsync(user, token, model.ConfirmPassword);

            if (rs.Succeeded)
            {
                return RedirectToAction(nameof(Profile), new { model.Id });
            }

            foreach (var error in rs.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(ChangePasswordModel.FromEntity(user));
        }

        public async Task<IActionResult> Claims(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, IncludeClaims = true, AsNoTracking = true });
            return View(ClaimsModel.FromEntity(user));
        }

        [HttpPost]
        public async Task<IActionResult> Claims(ClaimModel model)
        {

            await _commandBus.Send(new AddClaimCommand
            {
                Id = model.User.Id,
                Claim = new UserClaim
                {
                    Type = model.Type,
                    Value = model.Value,
                },
            });

            return RedirectToAction(nameof(Claims), new { id = model.Id});
        }

        public async Task<IActionResult> DeleteClaim(Guid userId, Guid claimId)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = userId, IncludeClaims = true, AsNoTracking = true });
            var claim = user.Claims.FirstOrDefault(x => x.Id == claimId);

            return View(ClaimModel.FromEntity(claim));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteClaim(ClaimModel model)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery
                {Id = model.User.Id, IncludeClaims = true, AsNoTracking = true});

            var claim = user.Claims.FirstOrDefault(x => x.Id == model.Id);
            await _commandBus.Send(new DeleteClaimCommand
            {
                Id = user.Id,
                Claim = claim,
            });

            return RedirectToAction(nameof(Claims), new {id = user.Id});
        }

        public async Task<IActionResult> Roles(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, IncludeRoles = true, AsNoTracking = true });

            var roles = await _commandBus.SendAsync(new GetRolesQuery { AsNoTracking = true });

            var model = new RolesModel
            {
                User = user,
                UserRoles = user.UserRoles.Select(x => new RoleModel { Role = x.Role, RoleId = x.RoleId }).ToList(),
                Roles = roles.Where(x => user.UserRoles.All(y => y.RoleId != x.Id)).ToList(),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Roles(RolesModel model)
        {
            await _commandBus.Send(new AddUserRoleCommand
            {
                Id = model.User.Id,
                Role = new UserRole
                {
                    RoleId = model.Role.RoleId,
                },
            });

            return RedirectToAction(nameof(Roles), new {model.User.Id});
        }

        public async Task<IActionResult> DeleteRole(Guid id, Guid roleId)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, IncludeRoles = true, AsNoTracking = true });
            var role = user.UserRoles.FirstOrDefault(x => x.RoleId == roleId);
            var model = new RoleModel { User = user, Role = role.Role };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(RoleModel model)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = model.User.Id, IncludeRoles = true, AsNoTracking = true });

            var role = user.UserRoles.FirstOrDefault(x => x.RoleId == model.Role.Id);

            await _commandBus.Send(new DeleteUserRoleCommand
            {
                Id = user.Id,
                Role = role,
            });

            return RedirectToAction(nameof(Roles), new { model.User.Id });
        }
    }
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/User/ChangePassword.cshtml
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@using IdentityServer4.Extensions
@model GHPCommerce.IS4Admin.Models.UserModels.ChangePasswordModel
@inject ICommandBus _commandBus
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != default && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <form asp-controller="User" asp-action="ChangePassword" Method="post">
    <div class="row">

        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Index">Users</a></li>
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Profile" asp-route-id="@Model.Id">@Model.UserName</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Change Password</li>
                </ol>
            </nav>
        </div>

        <div class="col-md-12">
            <h3>Change Password</h3>

            <div asp-validation-summary="All" class="text-danger"></div>

            <!--Hidden -->
            <input type="hidden" asp-for="Id" />

            <div class="card mt-3">
                <h5 class="card-header">Change Password</h5>
                <div class="card-body">

                    <!--Input - text -->
                    <div class="form-group row">
                        <label asp-for="UserName" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "User Name")
                        </label>
                        <div class="col-sm-9">
                            <input type="hidden" class="form-control" asp-for="UserName">
                            <h4>@Model.UserName</h4>
                        </div>
                    </div>

                    <!--Input - text -->
                    <div class="form-group row">
                        <label asp-for="Password" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "Password")
                        </label>
                        <div class="col-sm-9">
                            <input type="password" required class="form-control" asp-for="Password">
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>

                    <!--Input - text -->
                    <div class="form-group row">
                        <label asp-for="ConfirmPassword" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "Confirm Password")
                        </label>
                        <div class="col-sm-9">
                            <input type="password" required class="form-control" asp-for="ConfirmPassword">
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>

                    <!--Button-->
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">
                        </label>
                        <div class="col-sm-9">
                            <button type="submit" class="btn btn-danger">Change Password</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/User/Claims.cshtml
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@using IdentityServer4.Extensions
@model GHPCommerce.IS4Admin.Models.UserModels.ClaimsModel
@inject ICommandBus _commandBus
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != default && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <form id="user-claims-form" asp-controller="User" asp-action="Claims" Method="post">
    <div class="row">

        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Index">Users</a></li>
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Profile" asp-route-id="@Model.User.Id">@Model.User.UserName</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Claims</li>
                </ol>
            </nav>
        </div>

        <div class="col-md-12">
            <h3>Claims</h3>

            <div asp-validation-summary="All" class="text-danger"></div>

            <!--Hidden -->
            <input type="hidden" asp-for="User.Id" />

            <div class="card mt-3">
                <h5 class="card-header">Add Claim</h5>
                <div class="card-body">

                    <!--Select with tags-->
                    <div class="form-group row">
                        <label asp-for="Type" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "Type")
                        </label>
                        <div class="col-sm-9">
                            <picker id="Type" multiple-select="false" min-search-text="2"
                                    selected-item="@Model.Type"
                                    url="@Url.Action("GetClaims","IdentityResource")?claim"
                                    search-input-placeholder="search"
                                    selected-items-title="selected items"
                                    search-result-title="search result"
                                    suggested-items-title="suggested items"
                                    no-item-selected-title="no item selected"
                                    show-all-items-title="show all items"
                                    item-already-selected-title="item already selected"
                                    required="true" required-message="The Type is required">
                            </picker>

                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                    </div>

                    <!--Input - text -->
                    <div class="form-group row">
                        <label asp-for="Value" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "Value")
                        </label>
                        <div class="col-sm-9">
                            <input type="text" required class="form-control" asp-for="Value">
                            <span asp-validation-for="Value" class="text-danger"></span>
                        </div>
                    </div>

                    <!--Button-->
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">
                        </label>
                        <div class="col-sm-9">
                            <button type="submit" id="user-claims-button" class="btn btn-primary">Add</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md-12">
        <div class="card mt-3">
            <h5 class="card-header">Claims</h5>
            <div class="card-body">

                <div class="row table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Value</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var claim in Model.Claims)
                            {
                                <tr>
                                    <td>@claim.Type</td>
                                    <td>@claim.Value</td>
                                    <td><a asp-action="DeleteClaim" asp-route-claimId="@claim.Id" asp-route-userId="@Model.User.Id" class="btn btn-danger">Remove</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <div class="row">
                    <div class="col-12">
                        @*@await Html.PartialAsync("Common/Pager", new Pager { Action = "UserClaims", PageSize = Model.PageSize, TotalCount = Model.TotalCount })*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

@section scripts
	{
    <script>
        $(function () {
            //Disable enter for this form
            FormMvc.disableEnter($('#user-claims-form'));

            //Allow validate hidden field
            FormMvc.allowValidateHiddenField($('#user-claims-form'));
        });
    </script>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/User/Delete.cshtml
@inject ICommandBus _commandBus
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@using IdentityServer4.Extensions
@model GHPCommerce.Domain.Domain.Identity.User
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != null && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <div class="row">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Index">Users</a></li>
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Profile" asp-route-id="@Model.Id">@Model.UserName</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Delete</li>
                </ol>
            </nav>
        </div>
    </div>

    <form id="client-form" asp-controller="User" asp-action="Delete" Method="post">

        <h2>Delete</h2>

        <!--Hidden -->
        <input type="hidden" asp-for="Id" />
        <div class="card mt-3">
            <h5 class="card-header">Delete</h5>
            <div class="card-body">

                <!--Input - text -->
                <div class="form-group row">
                    <label asp-for="UserName" class="col-sm-3 col-form-label">
                        @await Html.PartialAsync("_Label", "User Name")
                    </label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" disabled="disabled" asp-for="UserName">
                    </div>
                </div>

                <!--Button-->
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                    </label>
                    <div class="col-sm-9">
                        <button type="submit" class="btn btn-danger">Delete User</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/User/DeleteClaim.cshtml
@using IdentityServer4.Extensions
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@model GHPCommerce.IS4Admin.Models.UserModels.ClaimModel
@inject ICommandBus _commandBus
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != default && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <form asp-controller="User" asp-action="DeleteClaim" Method="post">
    <div class="row">

        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Index">Users</a></li>
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Profile" asp-route-id="@Model.User.Id">@Model.User.UserName</a></li>
                    <li class="breadcrumb-item"><a asp-controller="User" asp-action="Claims" asp-route-id="@Model.User.Id">Claims</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Delete Claim</li>
                </ol>
            </nav>
        </div>

        <div class="col-md-12">
            <h3>Delete Claim</h3>

            <!--Hidden -->
            <input type="hidden" asp-for="User.Id" />
            <input type="hidden" asp-for="Id" />


            <div class="card mt-3">
                <h5 class="card-header">Delete Claim</h5>
                <div class="card-body">

                    <!--Input - text -->
                    <div class="form-group row">
                        <label asp-for="Type" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "Type")
                        </label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" disabled="disabled" asp-for="Type">
                        </div>
                    </div>

                    <!--Input - text -->
                    <div class="form-group row">
                        <label asp-for="Value" class="col-sm-3 col-form-label">
                            @await Html.PartialAsync("_Label", "Value")
                        </label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" disabled="disabled" asp-for="Value">
                        </div>
                    </div>

                    <!--Button-->
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">
                        </label>
                        <div class="col-sm-9">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/User/_Label.cshtml
@model string

@Model
<span data-toggle="tooltip" data-original-title="@Model"><span style="font-size: 12px;" class="oi oi-comment-square"></span></span>