src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Controllers/ApiResourceController.cs
using Microsoft.AspNetCore.Authorization;

namespace GHPCommerce.IS4Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Models.ApiResourceModels;
    using IdentityServer4.EntityFramework.DbContexts;
    using IdentityServer4.EntityFramework.Entities;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Newtonsoft.Json;
   
    public class ApiResourceController : Controller
    {
        private readonly ConfigurationDbContext _configurationDbContext;

        public ApiResourceController(ConfigurationDbContext configurationDbContext)
        {
            _configurationDbContext = configurationDbContext;
        }

        public IActionResult Index()
        {
            var apis = _configurationDbContext.ApiResources.ToList();
            return View(apis);
        }

        public IActionResult Add()
        {
            return View(nameof(Edit), new ApiResourceModel());
        }

        public IActionResult Edit(int id)
        {
            var identity = _configurationDbContext.ApiResources
                .Include(x => x.UserClaims)
                .FirstOrDefault(x => x.Id == id);
            return View(ApiResourceModel.FromEntity(identity));
        }

        [HttpPost]
        public IActionResult Edit(ApiResourceModel model)
        {
            ApiResource api;
            if (model.Id == 0)
            {
                api = new ApiResource
                {
                    UserClaims = new List<ApiResourceClaim>(),
                };
                _configurationDbContext.ApiResources.Add(api);
            }
            else
            {
                api = _configurationDbContext.ApiResources
                    .Include(x => x.UserClaims)
                    .FirstOrDefault(x => x.Id == model.Id);
                api.UserClaims.Clear();
            }

            model.UpdateEntity(api);

            if (!string.IsNullOrEmpty(model.UserClaimsItems))
            {
                var userClaims = JsonConvert.DeserializeObject<List<string>>(model.UserClaimsItems);

                api.UserClaims.AddRange(userClaims.Select(x => new ApiResourceClaim
                {
                    Type = x,
                }));
            }

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = api.Id });
        }

        public IActionResult Delete(int id)
        {
            var api = _configurationDbContext.ApiResources
                .FirstOrDefault(x => x.Id == id);
            return View(ApiResourceModel.FromEntity(api));
        }

        [HttpPost]
        public IActionResult Delete(ApiResourceModel model)
        {
            var api = _configurationDbContext.ApiResources
                .FirstOrDefault(x => x.Id == model.Id);

            _configurationDbContext.ApiResources.Remove(api);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Properties(int id)
        {
            var api = _configurationDbContext.ApiResources
                .Include(x => x.Properties)
                .FirstOrDefault(x => x.Id == id);
            return View(PropertiesModel.FromEntity(api));
        }

        [HttpPost]
        public IActionResult AddProperty(PropertiesModel model)
        {
            var api = _configurationDbContext.ApiResources
                .Include(x => x.Properties)
                .FirstOrDefault(x => x.Id == model.ApiResourceId);

            api.Properties.Add(new ApiResourceProperty
            {
                Key = model.Key,
                Value = model.Value,
            });

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Properties), new { id = api.Id });
        }

        [HttpGet]
        public IActionResult DeleteProperty(int id)
        {
            var prop = _configurationDbContext.Set<ApiResourceProperty>()
                .Include(x => x.ApiResource)
                .FirstOrDefault(x => x.Id == id);
            return View(ApiResourcePropertyModel.FromEntity(prop));
        }

        [HttpPost]
        public IActionResult DeleteProperty(ApiResourcePropertyModel model)
        {
            var api = _configurationDbContext.ApiResources
                            .Include(x => x.Properties)
                            .FirstOrDefault(x => x.Id == model.ApiResource.Id);
            var prop = api.Properties.FirstOrDefault(x => x.Id == model.Id);
            api.Properties.Remove(prop);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Properties), new { id = api.Id });
        }

        public IActionResult Secrets(int id)
        {
            var api = _configurationDbContext.ApiResources
                .Include(x => x.Secrets)
                .FirstOrDefault(x => x.Id == id);
            return View(SecretsModel.FromEntity(api));
        }

        [HttpPost]
        public IActionResult Secrets(SecretsModel model)
        {
            var api = _configurationDbContext.ApiResources
                .Include(x => x.Secrets)
                .FirstOrDefault(x => x.Id == model.ApiResourceId);

            var secret = new ApiSecret
            {
                Created = DateTime.UtcNow,
            };

            model.HashSecret();
            model.UpdateEntity(secret);
            api.Secrets.Add(secret);

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Secrets), new { id = api.Id });
        }

        [HttpGet]
        public IActionResult DeleteSecret(int id)
        {
            var secret = _configurationDbContext.Set<ApiSecret>()
                .Include(x => x.ApiResource)
                .FirstOrDefault(x => x.Id == id);
            return View(SecretModel.FromEntity(secret));
        }

        [HttpPost]
        public IActionResult DeleteSecret(SecretModel model)
        {
            var api = _configurationDbContext.ApiResources
                            .Include(x => x.Secrets)
                            .FirstOrDefault(x => x.Id == model.ApiResourceId);
            var secret = api.Secrets.FirstOrDefault(x => x.Id == model.Id);
            api.Secrets.Remove(secret);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Secrets), new { id = api.Id });
        }

        public IActionResult Scopes(int id)
        {
            var api = _configurationDbContext.ApiResources
                .Include(x => x.Scopes)
                .FirstOrDefault(x => x.Id == id);
            return View(ScopesModel.FromEntity(api));
        }

        public IActionResult EditScope(int apiId, int scopeId)
        {
            var api = _configurationDbContext.ApiResources
                .Include("Scopes.UserClaims")
                .FirstOrDefault(x => x.Id == apiId);

            if (scopeId != 0)
            {
                var scopeEntity = api.Scopes.FirstOrDefault(x => x.Id == scopeId);
                return View(ScopeModel.FromEntity(scopeEntity));
            }
            else
            {
                return View(new ScopeModel
                {
                    ApiResourceId = api.Id,
                    ApiResourceName = api.Name,
                    ApiResource = api,
                });
            }
        }

        [HttpPost]
        public IActionResult EditScope(ScopeModel model)
        {
            var api = _configurationDbContext.ApiResources
                .Include("Scopes.UserClaims")
                .FirstOrDefault(x => x.Id == model.ApiResourceId);

            ApiScope scope;
            if (model.Id == 0)
            {
                scope = new ApiScope
                {
                    UserClaims = new List<ApiScopeClaim>(),
                };
                api.Scopes.Add(scope);
            }
            else
            {
                scope = api.Scopes.FirstOrDefault(x => x.Id == model.Id);
                scope.UserClaims.Clear();
            }

            model.UpdateEntity(scope);

            if (!string.IsNullOrEmpty(model.UserClaimsItems))
            {
                var userClaims = JsonConvert.DeserializeObject<List<string>>(model.UserClaimsItems);

                scope.UserClaims.AddRange(userClaims.Select(x => new ApiScopeClaim
                {
                    Type = x,
                }));
            }

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Scopes), new { id = api.Id });
        }

        [HttpGet]
        public IActionResult DeleteScope(int apiId, int scopeId)
        {
            var scope = _configurationDbContext.Set<ApiScope>()
                .Include(x => x.ApiResource)
                .FirstOrDefault(x => x.Id == scopeId);
            return View(ScopeModel.FromEntity(scope));
        }

        [HttpPost]
        public IActionResult DeleteScope(ScopeModel model)
        {
            var api = _configurationDbContext.ApiResources
                            .Include(x => x.Scopes)
                            .FirstOrDefault(x => x.Id == model.ApiResourceId);
            var scope = api.Scopes.FirstOrDefault(x => x.Id == model.Id);
            api.Scopes.Remove(scope);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Scopes), new { id = api.Id });
        }
    }
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Controllers/IdentityResourceController.cs
using Microsoft.AspNetCore.Authorization;

namespace GHPCommerce.IS4Admin.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using   Models.IdentityResourceModels;
    using IdentityServer4.EntityFramework.DbContexts;
    using IdentityServer4.EntityFramework.Entities;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Newtonsoft.Json;
   // [Authorize(Roles = "SuperAdmin,Admin")]
    public class IdentityResourceController : Controller
    {
        private readonly ConfigurationDbContext _configurationDbContext;

        public IdentityResourceController(ConfigurationDbContext configurationDbContext)
        {
            _configurationDbContext = configurationDbContext;
        }

        public IActionResult Index()
        {
            var itentities = _configurationDbContext.IdentityResources.ToList();
            return View(itentities.ToModels().ToList());
        }

        public IActionResult Add()
        {
            return View(nameof(Edit), new IdentityResourceModel());
        }

        public IActionResult Edit(int id)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.UserClaims)
                .FirstOrDefault(x => x.Id == id);
            return View(identity.ToModel());
        }

        [HttpPost]
        public IActionResult Edit(IdentityResourceModel model)
        {
            IdentityResource identity;
            if (model.Id == 0)
            {
                identity = new IdentityResource
                {
                    UserClaims = new List<IdentityClaim>(),
                };
                _configurationDbContext.IdentityResources.Add(identity);
            }
            else
            {
                identity = _configurationDbContext.IdentityResources
                    .Include(x => x.UserClaims)
                    .FirstOrDefault(x => x.Id == model.Id);
                identity.UserClaims.Clear();
            }

            model.UpdateEntity(identity);

            if (!string.IsNullOrEmpty(model.UserClaimsItems))
            {
                model.UserClaims = JsonConvert.DeserializeObject<List<string>>(model.UserClaimsItems);

                identity.UserClaims.AddRange(model.UserClaims.Select(x => new IdentityClaim
                {
                    Type = x,
                }));
            }

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = identity.Id });
        }

        public IActionResult Delete(int id)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.UserClaims)
                .FirstOrDefault(x => x.Id == id);
            return View(identity.ToModel());
        }

        [HttpPost]
        public IActionResult Delete(IdentityResourceModel model)
        {
            var identity = _configurationDbContext.IdentityResources
                .FirstOrDefault(x => x.Id == model.Id);

            _configurationDbContext.IdentityResources.Remove(identity);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Properties(int id)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.Properties)
                .FirstOrDefault(x => x.Id == id);
            return View(PropertiesModel.FromEntity(identity));
        }

        [HttpPost]
        public IActionResult AddProperty(PropertiesModel model)
        {
            var identity = _configurationDbContext.IdentityResources
                .Include(x => x.Properties)
                .FirstOrDefault(x => x.Id == model.IdentityResourceId);

            identity.Properties.Add(new IdentityResourceProperty
            {
                Key = model.Key,
                Value = model.Value,
            });

            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Properties), new { id = identity.Id });
        }

        [HttpGet]
        public IActionResult DeleteProperty(int id)
        {
            var prop = _configurationDbContext.Set<IdentityResourceProperty>()
                .Include(x => x.IdentityResource)
                .FirstOrDefault(x => x.Id == id);
            return View(IdentityResourcePropertyModel.FromEntity(prop));
        }

        [HttpPost]
        public IActionResult DeleteProperty(IdentityResourcePropertyModel model)
        {
            var identity = _configurationDbContext.IdentityResources
                            .Include(x => x.Properties)
                            .FirstOrDefault(x => x.Id == model.IdentityResource.Id);
            var prop = identity.Properties.FirstOrDefault(x => x.Id == model.Id);
            identity.Properties.Remove(prop);
            _configurationDbContext.SaveChanges();

            return RedirectToAction(nameof(Properties), new { id = identity.Id });
        }

        public IActionResult GetClaims()
        {
            // http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
            var standardClaims = new List<string>
            {
                "name",
                "given_name",
                "family_name",
                "middle_name",
                "nickname",
                "preferred_username",
                "profile",
                "picture",
                "website",
                "gender",
                "birthdate",
                "zoneinfo",
                "locale",
                "address",
                "updated_at",
            };

            return Ok(standardClaims);
        }
    }
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/ApiResource/Delete.cshtml
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@using IdentityServer4.Extensions
@model GHPCommerce.IS4Admin.Models.ApiResourceModels.ApiResourceModel
@inject ICommandBus _commandBus
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != null && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <div class="row">
        <div class="col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="ApiResource" asp-action="Index">Api Resources</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a asp-controller="ApiResource" asp-action="Edit" asp-route-id="@Model.Id">@Model.Name</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Delete Api Resource</li>
                </ol>
            </nav>
        </div>

        <div class="col-12">
            <h2>Delete Api Resource</h2>
        </div>
    </div>

    <form asp-action="Delete" method="post">
        <!--Hidden -->
        <input type="hidden" asp-for="Id" />

        <div class="card mt-3">
            <h5 class="card-header">Delete Api Resource</h5>
            <div class="card-body">

                <!--Input - text -->
                <div class="form-group row">
                    <label asp-for="Name" class="col-sm-3 col-form-label">
                        @await Html.PartialAsync("_Label", "Name")
                    </label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" disabled="disabled" asp-for="Name">
                    </div>
                </div>

                <!--Button-->
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                    </label>
                    <div class="col-sm-9">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/ApiResource/Edit.cshtml
@using IdentityServer4.Extensions
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@model GHPCommerce.IS4Admin.Models.ApiResourceModels.ApiResourceModel
@inject ICommandBus _commandBus
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != null && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <div class="row">
    <div class="col-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="ApiResource" asp-action="Index">Api Resources</a></li>
                <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
            </ol>
        </nav>
    </div>

    <div class="col-12">
        <h2>Api Resources</h2>
    </div>
</div>

<form asp-action="Edit" method="post" id="api-resource-form">

    <div asp-validation-summary="All" class="text-danger"></div>

    <!--Hidden -->
    <input type="hidden" asp-for="Id" />

    <div class="card mt-3">
        <h5 class="card-header">Api Resources</h5>
        <div class="card-body">

            <!--Input - text -->
            <div class="form-group row">
                <label asp-for="Name" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Name")
                </label>
                <div class="col-sm-9">
                    <input type="text" required class="form-control" asp-for="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <!--Input - text -->
            <div class="form-group row">
                <label asp-for="DisplayName" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Display Name")
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="DisplayName">
                </div>
            </div>

            <!--Input - text -->
            <div class="form-group row">
                <label asp-for="Description" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Description")
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="Description">
                </div>
            </div>

            <!--Checkbox-->
            <div class="form-group row">
                <label asp-for="Enabled" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Enabled")
                </label>
                <div class="col-sm-9">
                    <toggle-button>
                        <input asp-for="Enabled" type="checkbox">
                    </toggle-button>
                </div>
            </div>

            @if (Model.Id != 0)
            {
                <!--Button-->
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                        @await Html.PartialAsync("_Label", "Scopes")
                    </label>
                    <div class="col-sm-9">
                        <a asp-action="Scopes" asp-route-id="@Model.Id" class="btn btn-primary">Manage Scopes</a>
                    </div>
                </div>
                <!--Button-->
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                        @await Html.PartialAsync("_Label", "Secrets")
                    </label>
                    <div class="col-sm-9">
                        <a asp-action="Secrets" asp-route-id="@Model.Id" class="btn btn-primary">Manage Secrets</a>
                    </div>
                </div>
                <!--Button-->
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">
                        @await Html.PartialAsync("_Label", "Properties")
                    </label>
                    <div class="col-sm-9">
                        <a asp-action="Properties" asp-route-id="@Model.Id" class="btn btn-primary">Manage Properties</a>
                    </div>
                </div>
            }

            <!--Select with tags-->
            <div class="form-group row">
                <label asp-for="UserClaims" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "User Claims")
                </label>
                <div class="col-sm-9">
                    <picker id="UserClaimsItems" multiple-select="true" min-search-text="2"
                            selected-items="@Model.UserClaims?.Select(x=>x.Type)?.ToList()" url="@Url.Action("GetClaims","IdentityResource")?claim"
                            search-input-placeholder="enter"
                            selected-items-title="selected items"
                            search-result-title="search result"
                            suggested-items-title="suggested items"
                            no-item-selected-title="no item selected"
                            show-all-items-title="show all items"
                            item-already-selected-title="item already selected">
                    </picker>
                </div>
            </div>

            <!--Button-->
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">
                </label>
                <div class="col-sm-9">
                    <button type="submit" id="api-resource-save-button" class="btn btn-primary">Save</button>
                    @if (Model.Id != 0)
                    {
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                    }
                </div>
            </div>
        </div>
    </div>

</form>
}

@section scripts
	{
    <script>
        $(function () {
            //Disable enter for this form
            FormMvc.disableEnter($('#api-resource-form'));
        });
    </script>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/ApiResource/EditScope.cshtml
@using GHPCommerce.Core.Shared.Contracts.Indentity.Queries
@using GHPCommerce.Domain.Domain.Commands
@using GHPCommerce.Domain.Domain.Identity
@using IdentityServer4.Extensions
@model GHPCommerce.IS4Admin.Models.ApiResourceModels.ScopeModel
@inject ICommandBus _commandBus
@{
    var q2 = User.IsAuthenticated()? 
        (from p in User.Claims where p.Type == "sub" select p.Value)?.FirstOrDefault() : String.Empty;
    var identity =!string.IsNullOrEmpty(q2)? _commandBus.SendAsync(new GetUserQuery() { IncludeRoles = true, Id = Guid.Parse(q2) })
        .GetAwaiter()
        .GetResult()  :default(User);
}
@if (identity != null && identity.UserRoles.Any(x => x.Role.Name.Equals("SuperAdmin")))
{
    <div class="row">
    <div class="col-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="ApiResource" asp-action="Index">Api Resources</a></li>
                <li class="breadcrumb-item"><a asp-controller="ApiResource" asp-action="Edit" asp-route-id="@Model.ApiResourceId">@Model.ApiResourceName</a></li>
                <li class="breadcrumb-item"><a asp-controller="ApiResource" asp-action="Scopes" asp-route-id="@Model.ApiResourceId">Scopes</a></li>

                @if (Model.Id != 0)
                {
                    <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
                }
                else
                {
                    <li class="breadcrumb-item active" aria-current="page">Add Scope</li>
                }
            </ol>
        </nav>
    </div>

    <div class="col-12">
        <h2>Scopes</h2>
    </div>
</div>

<form asp-action="EditScope" id="api-scope-form" method="post">

    <div asp-validation-summary="All" class="text-danger"></div>

    <!--Hidden -->
    <input type="hidden" asp-for="Id" />

    <!--Hidden -->
    <input type="hidden" asp-for="ApiResourceId" />

    <div class="card mt-3">
        <h5 class="card-header">Scope</h5>
        <div class="card-body">
            <!--Input - text -->
            <div class="form-group row">
                <label asp-for="Name" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Name")
                </label>
                <div class="col-sm-9">
                    <input type="text" required class="form-control" asp-for="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <!--Input - text -->
            <div class="form-group row">
                <label asp-for="DisplayName" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Display Name")
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="DisplayName">
                </div>
            </div>

            <!--Input - text -->
            <div class="form-group row">
                <label asp-for="Description" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Description")
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="Description">
                </div>
            </div>

            <!--Checkbox-->
            <div class="form-group row">
                <label asp-for="Required" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Required")
                </label>
                <div class="col-sm-9">
                    <toggle-button>
                        <input asp-for="Required" type="checkbox">
                    </toggle-button>
                </div>
            </div>

            <!--Checkbox-->
            <div class="form-group row">
                <label asp-for="Emphasize" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "Emphasize")
                </label>
                <div class="col-sm-9">
                    <toggle-button>
                        <input asp-for="Emphasize" type="checkbox">
                    </toggle-button>
                </div>
            </div>

            <!--Select with tags-->
            <div class="form-group row">
                <label asp-for="UserClaims" class="col-sm-3 col-form-label">
                    @await Html.PartialAsync("_Label", "User Claims")
                </label>
                <div class="col-sm-9">
                    <picker id="UserClaimsItems" multiple-select="true" min-search-text="2"
                            selected-items="@Model.UserClaims?.Select(x=>x.Type)?.ToList()" url="@Url.Action("GetClaims","IdentityResource")?claim"
                            search-input-placeholder="enter"
                            selected-items-title="selected items"
                            search-result-title="search result"
                            suggested-items-title="suggested items"
                            no-item-selected-title="no item selected"
                            show-all-items-title="show all items"
                            item-already-selected-title="item already selected">
                    </picker>
                </div>
            </div>

            <!--Button-->
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">
                </label>
                <div class="col-sm-9">
                    <button type="submit" asp-action="EditScope" id="api-scope-save-button" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>

</form>
}

@section scripts
	{
    <script>
        $(function () {
            //Disable enter for this form
            FormMvc.disableEnter($('#api-scope-form'));
        });
    </script>
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/ApiResource/_Label.cshtml
@model string

@Model
<span data-toggle="tooltip" data-original-title="@Model"><span style="font-size: 12px;" class="oi oi-comment-square"></span></span>