src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;

namespace GHPCommerce.IS4Admin.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Application.Membership.Roles.Commands;
    using Application.Membership.Roles.Queries;
    using GHPCommerce.Domain.Domain.Commands;
    using GHPCommerce.Domain.Domain.Identity;
    using Models.RoleModels;
    using Microsoft.AspNetCore.Mvc;

  //  [Authorize(Roles = "SuperAdmin,Admin")]
    public class RoleController : Controller
    {
        private readonly ICommandBus _commandBus;
       
        public RoleController(ICommandBus commandBus)
        {
            _commandBus = commandBus;
           
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _commandBus.SendAsync(new GetRolesQuery { AsNoTracking = true });
            return View(roles);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            Role role;
            if (id == Guid.Empty)
                role = new Role();
            else
                role = await _commandBus.SendAsync(new GetRoleQuery { Id = id, AsNoTracking = true });
            var model = role;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Role model)
        {
            Role role;

            if (model.Id == Guid.Empty)
            {
                role = new Role
                {
                    Name = model.Name,
                    NormalizedName = model.Name.ToUpper(),
                };

                await _commandBus.Send(new AddUpdateRoleCommand { Role = role });
            }
            else
            {
                role = await _commandBus.SendAsync(new GetRoleQuery { Id = model.Id });
                role.Name = model.Name;
                role.NormalizedName = model.Name.ToUpper();
                await _commandBus.Send(new AddUpdateRoleCommand { Role = role });
            }

            return RedirectToAction(nameof(Edit), new { role.Id });
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var role = await _commandBus.SendAsync(new GetRoleQuery { Id = id, AsNoTracking = true });
            return View(role);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Role model)
        {
            await _commandBus.Send(new DeleteRoleCommand { Id = model.Id });

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Claims(Guid id)
        {
            var role = await _commandBus.SendAsync(new GetRoleQuery { Id = id, IncludeClaims = true, AsNoTracking = true });

            return View(ClaimsModel.FromEntity(role));
        }

        [HttpPost]
        public async Task<IActionResult> Claims(ClaimModel model)
        {
            var claim = new RoleClaim
            {
                Type = model.Type,
                Value = model.Value,
            };

            await _commandBus.Send(new AddRoleClaimCommand { Id = model.Role.Id, Claim = claim });

            return RedirectToAction(nameof(Claims), new { id = model.Role.Id });
        }

        public async Task<IActionResult> DeleteClaim(Guid roleId, Guid claimId)
        {
            var role = await _commandBus.SendAsync(new GetRoleQuery { Id = roleId, IncludeClaims = true, AsNoTracking = true });
            var claim = role.Claims.FirstOrDefault(x => x.Id == claimId);

            return View(ClaimModel.FromEntity(claim));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteClaim(ClaimModel model)
        {
            var role = await _commandBus.SendAsync(new GetRoleQuery { Id = model.Role.Id, IncludeClaims = true });

            var claim = role.Claims.FirstOrDefault(x => x.Id == model.Id);

            await _commandBus.Send(new DeleteRoleClaimCommand { Id = role.Id, Claim = claim });

            return RedirectToAction(nameof(Claims), new { id = role.Id });
        }

        public async Task<IActionResult> Users(Guid id)
        {
            var role = await _commandBus.SendAsync(new GetRoleQuery { Id = id, IncludeUsers = true, AsNoTracking = true });

            var users = role.UserRoles.Select(x => x.User).ToList();
            var model = new UsersModel
            {
                Role = role,
                Users = users,
            };

            return View(model);
        }
    }
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Controllers/UserController.cs
using GHPCommerce.Core.Shared.Contracts.Indentity.Queries;
using Microsoft.AspNetCore.Authorization;

namespace GHPCommerce.IS4Admin.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Application.Membership.Roles.Queries;
    using Application.Membership.Users.Commands;
    using Application.Membership.Users.Queries;
    using CrossCuttingConcerns.OS;
    using GHPCommerce.Domain.Domain.Commands;
    using GHPCommerce.Domain.Domain.Identity;
    using Models.UserModels;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

//    [Authorize(Roles = "SuperAdmin,Admin")]
    public class UserController : Controller
    {
       
        private readonly ICommandBus _commandBus;
        private readonly UserManager<User> _userManager;
        private readonly IDateTimeProvider _dateTimeProvider;

        public UserController(ICommandBus commandBus,
            UserManager<User> userManager,
            ILogger<UserController> logger,
            IDateTimeProvider dateTimeProvider)
        {
           
            _commandBus = commandBus;
            _userManager = userManager;
            _dateTimeProvider = dateTimeProvider;
            logger.LogInformation("UserController");
        }

        public async Task<IActionResult> Index()
        {
            var users = await _commandBus.SendAsync(new GetUsersQuery { AsNoTracking = true });
            return View(users);
        }

        public async Task<IActionResult> Profile(Guid id)
        {
            var user = id != Guid.Empty
                ? await _commandBus.SendAsync(new GetUserQuery { Id = id, AsNoTracking = true })
                : new User();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(User model)
        {
            User user;
            if (model.Id != Guid.Empty)
            {
                user = await _commandBus.SendAsync(new GetUserQuery { Id = model.Id });
            }
            else
            {
                user = new User();
            }

            user.UserName = model.UserName;
            user.NormalizedUserName = model.UserName.ToUpper();
            user.Email = model.Email;
            user.NormalizedEmail = model.Email.ToUpper();
            user.EmailConfirmed = model.EmailConfirmed;
            user.PhoneNumber = model.PhoneNumber;
            user.PhoneNumberConfirmed = model.PhoneNumberConfirmed;
            user.TwoFactorEnabled = model.TwoFactorEnabled;
            user.LockoutEnabled = model.LockoutEnabled;
            user.LockoutEnd = model.LockoutEnd;
            user.AccessFailedCount = model.AccessFailedCount;

            _ = model.Id != Guid.Empty
                 ? await _userManager.UpdateAsync(user)
                 : await _userManager.CreateAsync(user);

            return RedirectToAction(nameof(Profile), new { user.Id });
        }

        public async Task<IActionResult> ChangePassword(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, AsNoTracking = true });
            return View(ChangePasswordModel.FromEntity(user));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, AsNoTracking = true });
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(User model)
        {
            await _commandBus.Send(new DeleteUserCommand { Id = model.Id });
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _commandBus.SendAsync(new GetUserQuery { Id = model.Id });
            var token = await _userManager.GeneratePasswordResetTokenAsync(user);
            var rs = await _userManager.ResetPasswordAsync(user, token, model.ConfirmPassword);

            if (rs.Succeeded)
            {
                return RedirectToAction(nameof(Profile), new { model.Id });
            }

            foreach (var error in rs.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(ChangePasswordModel.FromEntity(user));
        }

        public async Task<IActionResult> Claims(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, IncludeClaims = true, AsNoTracking = true });
            return View(ClaimsModel.FromEntity(user));
        }

        [HttpPost]
        public async Task<IActionResult> Claims(ClaimModel model)
        {

            await _commandBus.Send(new AddClaimCommand
            {
                Id = model.User.Id,
                Claim = new UserClaim
                {
                    Type = model.Type,
                    Value = model.Value,
                },
            });

            return RedirectToAction(nameof(Claims), new { id = model.Id});
        }

        public async Task<IActionResult> DeleteClaim(Guid userId, Guid claimId)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = userId, IncludeClaims = true, AsNoTracking = true });
            var claim = user.Claims.FirstOrDefault(x => x.Id == claimId);

            return View(ClaimModel.FromEntity(claim));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteClaim(ClaimModel model)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery
                {Id = model.User.Id, IncludeClaims = true, AsNoTracking = true});

            var claim = user.Claims.FirstOrDefault(x => x.Id == model.Id);
            await _commandBus.Send(new DeleteClaimCommand
            {
                Id = user.Id,
                Claim = claim,
            });

            return RedirectToAction(nameof(Claims), new {id = user.Id});
        }

        public async Task<IActionResult> Roles(Guid id)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, IncludeRoles = true, AsNoTracking = true });

            var roles = await _commandBus.SendAsync(new GetRolesQuery { AsNoTracking = true });

            var model = new RolesModel
            {
                User = user,
                UserRoles = user.UserRoles.Select(x => new RoleModel { Role = x.Role, RoleId = x.RoleId }).ToList(),
                Roles = roles.Where(x => user.UserRoles.All(y => y.RoleId != x.Id)).ToList(),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Roles(RolesModel model)
        {
            await _commandBus.Send(new AddUserRoleCommand
            {
                Id = model.User.Id,
                Role = new UserRole
                {
                    RoleId = model.Role.RoleId,
                },
            });

            return RedirectToAction(nameof(Roles), new {model.User.Id});
        }

        public async Task<IActionResult> DeleteRole(Guid id, Guid roleId)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = id, IncludeRoles = true, AsNoTracking = true });
            var role = user.UserRoles.FirstOrDefault(x => x.RoleId == roleId);
            var model = new RoleModel { User = user, Role = role.Role };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(RoleModel model)
        {
            var user = await _commandBus.SendAsync(new GetUserQuery { Id = model.User.Id, IncludeRoles = true, AsNoTracking = true });

            var role = user.UserRoles.FirstOrDefault(x => x.RoleId == model.Role.Id);

            await _commandBus.Send(new DeleteUserRoleCommand
            {
                Id = user.Id,
                Role = role,
            });

            return RedirectToAction(nameof(Roles), new { model.User.Id });
        }
    }
}

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/Shared/Redirect.cshtml
@model GHPCommerce.IS4Admin.Quickstart.Account.RedirectViewModel

<h1>You are now being returned to the application.</h1>
<p>Once complete, you may close this tab</p>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/Shared/_Layout.cshtml
@using IdentityServer4.Extensions
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IdentityServer4</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/css/bundle.min.css" />
    <link rel="stylesheet" href="~/css/web.css" />
</head>
<body>
    <div class="menu d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <!--Site name -->
        <h3 class="menu-logo my-0 mr-md-auto font-weight-normal">
            <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/icon.png" class="icon-banner">
                IdentityServer4
            </a>
        </h3>

        <!--Menu item -->
       @if (User.Identity.IsAuthenticated)
       {
           <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
               <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                   Configuration
               </button>
               <div class="dropdown-menu">
                   <a class="dropdown-item" asp-area="" asp-controller="Client" asp-action="Index">Clients</a>
                   <div class="dropdown-divider"></div>
                   <a class="dropdown-item" asp-area="" asp-controller="IdentityResource" asp-action="Index">Identity Resources</a>
                   <div class="dropdown-divider"></div>
                   <a class="dropdown-item" asp-area="" asp-controller="ApiResource" asp-action="Index">Api Resources</a>
                   <div class="dropdown-divider"></div>
                   <a class="dropdown-item" asp-area="" asp-controller="Grants" asp-action="Index">Persisted Grants</a>
               </div>
           </div>

           <!--Menu item -->
           <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
               <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                   User Management
               </button>
               <div class="dropdown-menu">
                   <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                   <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
               </div>
           </div>
       }

        <!--Menu item -->
        @if (User.Identity.IsAuthenticated)
        {
            <a class="menu-item my-2 btn btn-outline-primary" asp-action="Logout" asp-controller="Account">@User.GetDisplayName() - Logout</a>
        }
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <mini-profiler />
    <script src="~/js/bundle.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/Shared/_ScopeListItem.cshtml
@model GHPCommerce.IS4Admin.Quickstart.Consent.ScopeViewModel

<li class="list-group-item">
    <div class="toggle-button__input">
        <toggle-button>
            <input class="consent-scopecheck"
                   type="checkbox"
                   name="ScopesConsented"
                   id="scopes_@Model.Name"
                   value="@Model.Name"
                   checked="@Model.Checked"
                   disabled="@Model.Required" />
        </toggle-button>
    </div>
    <div class="toggle-button__text">
        @if (Model.Required)
        {
            <input type="hidden"
                   name="ScopesConsented"
                   value="@Model.Name" />
        }
        <strong>@Model.DisplayName</strong>
        @if (Model.Emphasize)
        {
            <i class="fa fa-exclamation-circle"></i>
        }
    </div>
    @if (Model.Required)
    {
        <div class="toggle-button__text">
            <span><em>(required)</em></span>
        </div>
    }
    @if (Model.Description != null)
    {
        <div class="consent-description">
            <label for="scopes_@Model.Name">@Model.Description</label>
        </div>
    }
</li>

src/GHPCommerce.BackEnd/GHPCommerce.IS4Admin/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}